// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: pb/connect.rpc.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectSendClientRetCode int32

const (
	ConnectSendClientRetCode_CR_Unknow  ConnectSendClientRetCode = 0    //未知系统异常
	ConnectSendClientRetCode_CR_Success ConnectSendClientRetCode = 2001 //发送成功
	ConnectSendClientRetCode_CR_Offline ConnectSendClientRetCode = 2002 //用户设备离线
	ConnectSendClientRetCode_CR_Error   ConnectSendClientRetCode = 5001 //发送异常
)

// Enum value maps for ConnectSendClientRetCode.
var (
	ConnectSendClientRetCode_name = map[int32]string{
		0:    "CR_Unknow",
		2001: "CR_Success",
		2002: "CR_Offline",
		5001: "CR_Error",
	}
	ConnectSendClientRetCode_value = map[string]int32{
		"CR_Unknow":  0,
		"CR_Success": 2001,
		"CR_Offline": 2002,
		"CR_Error":   5001,
	}
)

func (x ConnectSendClientRetCode) Enum() *ConnectSendClientRetCode {
	p := new(ConnectSendClientRetCode)
	*p = x
	return p
}

func (x ConnectSendClientRetCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectSendClientRetCode) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_connect_rpc_proto_enumTypes[0].Descriptor()
}

func (ConnectSendClientRetCode) Type() protoreflect.EnumType {
	return &file_pb_connect_rpc_proto_enumTypes[0]
}

func (x ConnectSendClientRetCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectSendClientRetCode.Descriptor instead.
func (ConnectSendClientRetCode) EnumDescriptor() ([]byte, []int) {
	return file_pb_connect_rpc_proto_rawDescGZIP(), []int{0}
}

type ConnectSendClientReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` //客户端session
	ServerId  uint32 `protobuf:"varint,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`   //
	Command   Packet `protobuf:"varint,3,opt,name=command,proto3,enum=pb.Packet" json:"command,omitempty"`      //命令
	Payload   []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                      //数据包
}

func (x *ConnectSendClientReq) Reset() {
	*x = ConnectSendClientReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_connect_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectSendClientReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSendClientReq) ProtoMessage() {}

func (x *ConnectSendClientReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_connect_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSendClientReq.ProtoReflect.Descriptor instead.
func (*ConnectSendClientReq) Descriptor() ([]byte, []int) {
	return file_pb_connect_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectSendClientReq) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ConnectSendClientReq) GetServerId() uint32 {
	if x != nil {
		return x.ServerId
	}
	return 0
}

func (x *ConnectSendClientReq) GetCommand() Packet {
	if x != nil {
		return x.Command
	}
	return Packet_PacketNone
}

func (x *ConnectSendClientReq) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ConnectSendClientRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode ConnectSendClientRetCode `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3,enum=pb.ConnectSendClientRetCode" json:"ret_code,omitempty"` //响应
}

func (x *ConnectSendClientRes) Reset() {
	*x = ConnectSendClientRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_connect_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectSendClientRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectSendClientRes) ProtoMessage() {}

func (x *ConnectSendClientRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_connect_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectSendClientRes.ProtoReflect.Descriptor instead.
func (*ConnectSendClientRes) Descriptor() ([]byte, []int) {
	return file_pb_connect_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectSendClientRes) GetRetCode() ConnectSendClientRetCode {
	if x != nil {
		return x.RetCode
	}
	return ConnectSendClientRetCode_CR_Unknow
}

var File_pb_connect_rpc_proto protoreflect.FileDescriptor

var file_pb_connect_rpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x2e, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x70, 0x62, 0x2f, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x14,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x24, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x4f, 0x0a, 0x14, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x08, 0x72, 0x65, 0x74, 0x5f,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70, 0x62, 0x2e,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x6e, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74, 0x43, 0x6f, 0x64,
	0x65, 0x2a, 0x5a, 0x0a, 0x18, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x53, 0x65, 0x6e, 0x64,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0d, 0x0a,
	0x09, 0x43, 0x52, 0x5f, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0a,
	0x43, 0x52, 0x5f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0xd1, 0x0f, 0x12, 0x0f, 0x0a,
	0x0a, 0x43, 0x52, 0x5f, 0x4f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0xd2, 0x0f, 0x12, 0x0d,
	0x0a, 0x08, 0x43, 0x52, 0x5f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x89, 0x27, 0x42, 0x0e, 0x5a,
	0x0c, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x50, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_connect_rpc_proto_rawDescOnce sync.Once
	file_pb_connect_rpc_proto_rawDescData = file_pb_connect_rpc_proto_rawDesc
)

func file_pb_connect_rpc_proto_rawDescGZIP() []byte {
	file_pb_connect_rpc_proto_rawDescOnce.Do(func() {
		file_pb_connect_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_connect_rpc_proto_rawDescData)
	})
	return file_pb_connect_rpc_proto_rawDescData
}

var file_pb_connect_rpc_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_connect_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_connect_rpc_proto_goTypes = []interface{}{
	(ConnectSendClientRetCode)(0), // 0: pb.ConnectSendClientRetCode
	(*ConnectSendClientReq)(nil),  // 1: pb.ConnectSendClientReq
	(*ConnectSendClientRes)(nil),  // 2: pb.ConnectSendClientRes
	(Packet)(0),                   // 3: pb.Packet
}
var file_pb_connect_rpc_proto_depIdxs = []int32{
	3, // 0: pb.ConnectSendClientReq.command:type_name -> pb.Packet
	0, // 1: pb.ConnectSendClientRes.ret_code:type_name -> pb.ConnectSendClientRetCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_connect_rpc_proto_init() }
func file_pb_connect_rpc_proto_init() {
	if File_pb_connect_rpc_proto != nil {
		return
	}
	file_pb_packet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_connect_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectSendClientReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_connect_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectSendClientRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_connect_rpc_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_connect_rpc_proto_goTypes,
		DependencyIndexes: file_pb_connect_rpc_proto_depIdxs,
		EnumInfos:         file_pb_connect_rpc_proto_enumTypes,
		MessageInfos:      file_pb_connect_rpc_proto_msgTypes,
	}.Build()
	File_pb_connect_rpc_proto = out.File
	file_pb_connect_rpc_proto_rawDesc = nil
	file_pb_connect_rpc_proto_goTypes = nil
	file_pb_connect_rpc_proto_depIdxs = nil
}
