// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: pb/packet.msg.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 消息类型枚举
type PacketMsgType int32

const (
	PacketMsgType_None  PacketMsgType = 0
	PacketMsgType_Text  PacketMsgType = 1 //文字消息
	PacketMsgType_Image PacketMsgType = 2 //图片消息
	PacketMsgType_Audio PacketMsgType = 3 //语音消息
	PacketMsgType_Video PacketMsgType = 4 //视频消息
	PacketMsgType_File  PacketMsgType = 5 //文件消息
)

// Enum value maps for PacketMsgType.
var (
	PacketMsgType_name = map[int32]string{
		0: "None",
		1: "Text",
		2: "Image",
		3: "Audio",
		4: "Video",
		5: "File",
	}
	PacketMsgType_value = map[string]int32{
		"None":  0,
		"Text":  1,
		"Image": 2,
		"Audio": 3,
		"Video": 4,
		"File":  5,
	}
)

func (x PacketMsgType) Enum() *PacketMsgType {
	p := new(PacketMsgType)
	*p = x
	return p
}

func (x PacketMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PacketMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_packet_msg_proto_enumTypes[0].Descriptor()
}

func (PacketMsgType) Type() protoreflect.EnumType {
	return &file_pb_packet_msg_proto_enumTypes[0]
}

func (x PacketMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PacketMsgType.Descriptor instead.
func (PacketMsgType) EnumDescriptor() ([]byte, []int) {
	return file_pb_packet_msg_proto_rawDescGZIP(), []int{0}
}

// 文字消息
type TextMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content string `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` //文字内容
}

func (x *TextMsg) Reset() {
	*x = TextMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextMsg) ProtoMessage() {}

func (x *TextMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextMsg.ProtoReflect.Descriptor instead.
func (*TextMsg) Descriptor() ([]byte, []int) {
	return file_pb_packet_msg_proto_rawDescGZIP(), []int{0}
}

func (x *TextMsg) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 图片消息
type ImageMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url    string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`        //图片Url地址
	Md5    string `protobuf:"bytes,2,opt,name=md5,proto3" json:"md5,omitempty"`        //图片MD5
	Width  int32  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`   //图片宽度
	Height int32  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"` //图片高度
	Size   int32  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`     //图片大小
}

func (x *ImageMsg) Reset() {
	*x = ImageMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImageMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageMsg) ProtoMessage() {}

func (x *ImageMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageMsg.ProtoReflect.Descriptor instead.
func (*ImageMsg) Descriptor() ([]byte, []int) {
	return file_pb_packet_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ImageMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ImageMsg) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

func (x *ImageMsg) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *ImageMsg) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *ImageMsg) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// 语音消息
type AudioMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`            //语音Url地址
	Duration uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` //语音时长,单位秒
	Size     int32  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`         //语音文件大小
	Md5      string `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`            //语音MD5
}

func (x *AudioMsg) Reset() {
	*x = AudioMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AudioMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioMsg) ProtoMessage() {}

func (x *AudioMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioMsg.ProtoReflect.Descriptor instead.
func (*AudioMsg) Descriptor() ([]byte, []int) {
	return file_pb_packet_msg_proto_rawDescGZIP(), []int{2}
}

func (x *AudioMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *AudioMsg) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AudioMsg) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *AudioMsg) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type VideoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url      string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`            //视频url地址
	Duration uint32 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"` //视频时长,单位秒
	Size     int32  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`         //视频文件大小
	Md5      string `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`            //视频MD5
}

func (x *VideoMsg) Reset() {
	*x = VideoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VideoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMsg) ProtoMessage() {}

func (x *VideoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMsg.ProtoReflect.Descriptor instead.
func (*VideoMsg) Descriptor() ([]byte, []int) {
	return file_pb_packet_msg_proto_rawDescGZIP(), []int{3}
}

func (x *VideoMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VideoMsg) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoMsg) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *VideoMsg) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

type FileMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`    //文件url地址
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`  //文件名称
	Size int32  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` //文件大小
	Md5  string `protobuf:"bytes,4,opt,name=md5,proto3" json:"md5,omitempty"`    //文件MD5
}

func (x *FileMsg) Reset() {
	*x = FileMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMsg) ProtoMessage() {}

func (x *FileMsg) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMsg.ProtoReflect.Descriptor instead.
func (*FileMsg) Descriptor() ([]byte, []int) {
	return file_pb_packet_msg_proto_rawDescGZIP(), []int{4}
}

func (x *FileMsg) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *FileMsg) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileMsg) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileMsg) GetMd5() string {
	if x != nil {
		return x.Md5
	}
	return ""
}

var File_pb_packet_msg_proto protoreflect.FileDescriptor

var file_pb_packet_msg_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6d, 0x73, 0x67, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x23, 0x0a, 0x07, 0x54, 0x65, 0x78,
	0x74, 0x4d, 0x73, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x70,
	0x0a, 0x08, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x64, 0x35, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65,
	0x22, 0x5e, 0x0a, 0x08, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35,
	0x22, 0x5e, 0x0a, 0x08, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69,
	0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35,
	0x22, 0x55, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x65, 0x4d, 0x73, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x64, 0x35, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6d, 0x64, 0x35, 0x2a, 0x4e, 0x0a, 0x0d, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x6f, 0x6e, 0x65,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x49, 0x6d, 0x61, 0x67, 0x65, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x75, 0x64, 0x69, 0x6f,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x69, 0x64, 0x65, 0x6f, 0x10, 0x04, 0x12, 0x08, 0x0a,
	0x04, 0x46, 0x69, 0x6c, 0x65, 0x10, 0x05, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_packet_msg_proto_rawDescOnce sync.Once
	file_pb_packet_msg_proto_rawDescData = file_pb_packet_msg_proto_rawDesc
)

func file_pb_packet_msg_proto_rawDescGZIP() []byte {
	file_pb_packet_msg_proto_rawDescOnce.Do(func() {
		file_pb_packet_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_packet_msg_proto_rawDescData)
	})
	return file_pb_packet_msg_proto_rawDescData
}

var file_pb_packet_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_packet_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pb_packet_msg_proto_goTypes = []interface{}{
	(PacketMsgType)(0), // 0: pb.PacketMsgType
	(*TextMsg)(nil),    // 1: pb.TextMsg
	(*ImageMsg)(nil),   // 2: pb.ImageMsg
	(*AudioMsg)(nil),   // 3: pb.AudioMsg
	(*VideoMsg)(nil),   // 4: pb.VideoMsg
	(*FileMsg)(nil),    // 5: pb.FileMsg
}
var file_pb_packet_msg_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_packet_msg_proto_init() }
func file_pb_packet_msg_proto_init() {
	if File_pb_packet_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_packet_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImageMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AudioMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VideoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_packet_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_packet_msg_proto_goTypes,
		DependencyIndexes: file_pb_packet_msg_proto_depIdxs,
		EnumInfos:         file_pb_packet_msg_proto_enumTypes,
		MessageInfos:      file_pb_packet_msg_proto_msgTypes,
	}.Build()
	File_pb_packet_msg_proto = out.File
	file_pb_packet_msg_proto_rawDesc = nil
	file_pb_packet_msg_proto_goTypes = nil
	file_pb_packet_msg_proto_depIdxs = nil
}
