// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: pb/packet.event.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 好友申请,验证请求事件
type FriendRequestEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                         //验证消息ID
	FromUid      uint64 `protobuf:"varint,2,opt,name=from_uid,json=fromUid,proto3" json:"from_uid,omitempty"`                //请求方UID
	ToUid        uint64 `protobuf:"varint,3,opt,name=to_uid,json=toUid,proto3" json:"to_uid,omitempty"`                      //接收方UID
	RequestTime  int64  `protobuf:"varint,4,opt,name=request_time,json=requestTime,proto3" json:"request_time,omitempty"`    //请求添加时间
	Reason       string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`                                  //添加原因
	Status       int32  `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`                                 //验证状态
	ResponseTime int64  `protobuf:"varint,7,opt,name=response_time,json=responseTime,proto3" json:"response_time,omitempty"` //处理时间
	RejectReason string `protobuf:"bytes,8,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`  //拒绝原因
}

func (x *FriendRequestEvent) Reset() {
	*x = FriendRequestEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_event_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestEvent) ProtoMessage() {}

func (x *FriendRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_event_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestEvent.ProtoReflect.Descriptor instead.
func (*FriendRequestEvent) Descriptor() ([]byte, []int) {
	return file_pb_packet_event_proto_rawDescGZIP(), []int{0}
}

func (x *FriendRequestEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FriendRequestEvent) GetFromUid() uint64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *FriendRequestEvent) GetToUid() uint64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *FriendRequestEvent) GetRequestTime() int64 {
	if x != nil {
		return x.RequestTime
	}
	return 0
}

func (x *FriendRequestEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *FriendRequestEvent) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FriendRequestEvent) GetResponseTime() int64 {
	if x != nil {
		return x.ResponseTime
	}
	return 0
}

func (x *FriendRequestEvent) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

// 好友变动事件
type FriendChangeEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FriendId uint64  `protobuf:"varint,1,opt,name=friend_id,json=friendId,proto3" json:"friend_id,omitempty"` //好友的用户Id
	Friend   *Friend `protobuf:"bytes,2,opt,name=friend,proto3" json:"friend,omitempty"`                      //好友信息
	IsFriend bool    `protobuf:"varint,3,opt,name=is_friend,json=isFriend,proto3" json:"is_friend,omitempty"` //true=新好友,false=删除好友
	Time     int64   `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`                         //事件时间
}

func (x *FriendChangeEvent) Reset() {
	*x = FriendChangeEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_event_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendChangeEvent) ProtoMessage() {}

func (x *FriendChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_event_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendChangeEvent.ProtoReflect.Descriptor instead.
func (*FriendChangeEvent) Descriptor() ([]byte, []int) {
	return file_pb_packet_event_proto_rawDescGZIP(), []int{1}
}

func (x *FriendChangeEvent) GetFriendId() uint64 {
	if x != nil {
		return x.FriendId
	}
	return 0
}

func (x *FriendChangeEvent) GetFriend() *Friend {
	if x != nil {
		return x.Friend
	}
	return nil
}

func (x *FriendChangeEvent) GetIsFriend() bool {
	if x != nil {
		return x.IsFriend
	}
	return false
}

func (x *FriendChangeEvent) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_pb_packet_event_proto protoreflect.FileDescriptor

var file_pb_packet_event_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x62, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x70, 0x62, 0x2f,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x62,
	0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x70, 0x62, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e,
	0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x12, 0x46, 0x72,
	0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x19, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x74,
	0x6f, 0x5f, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x74, 0x6f, 0x55,
	0x69, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65,
	0x6a, 0x65, 0x63, 0x74, 0x5f, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x72, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22,
	0x85, 0x01, 0x0a, 0x11, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65,
	0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64,
	0x49, 0x64, 0x12, 0x22, 0x0a, 0x06, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x62, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x06,
	0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x73, 0x5f, 0x66, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x50, 0x00, 0x50, 0x01, 0x50, 0x02, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_packet_event_proto_rawDescOnce sync.Once
	file_pb_packet_event_proto_rawDescData = file_pb_packet_event_proto_rawDesc
)

func file_pb_packet_event_proto_rawDescGZIP() []byte {
	file_pb_packet_event_proto_rawDescOnce.Do(func() {
		file_pb_packet_event_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_packet_event_proto_rawDescData)
	})
	return file_pb_packet_event_proto_rawDescData
}

var file_pb_packet_event_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pb_packet_event_proto_goTypes = []interface{}{
	(*FriendRequestEvent)(nil), // 0: pb.FriendRequestEvent
	(*FriendChangeEvent)(nil),  // 1: pb.FriendChangeEvent
	(*Friend)(nil),             // 2: pb.Friend
}
var file_pb_packet_event_proto_depIdxs = []int32{
	2, // 0: pb.FriendChangeEvent.friend:type_name -> pb.Friend
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_packet_event_proto_init() }
func file_pb_packet_event_proto_init() {
	if File_pb_packet_event_proto != nil {
		return
	}
	file_pb_packet_proto_init()
	file_pb_packet_entity_proto_init()
	file_pb_packet_msg_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_packet_event_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendRequestEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_event_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendChangeEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_packet_event_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_packet_event_proto_goTypes,
		DependencyIndexes: file_pb_packet_event_proto_depIdxs,
		MessageInfos:      file_pb_packet_event_proto_msgTypes,
	}.Build()
	File_pb_packet_event_proto = out.File
	file_pb_packet_event_proto_rawDesc = nil
	file_pb_packet_event_proto_goTypes = nil
	file_pb_packet_event_proto_depIdxs = nil
}
