// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.5
// source: pb/packet.self.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 获取当前用户信息
type PacketGetProfileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PacketGetProfileReq) Reset() {
	*x = PacketGetProfileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_self_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketGetProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketGetProfileReq) ProtoMessage() {}

func (x *PacketGetProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_self_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketGetProfileReq.ProtoReflect.Descriptor instead.
func (*PacketGetProfileReq) Descriptor() ([]byte, []int) {
	return file_pb_packet_self_proto_rawDescGZIP(), []int{0}
}

// 用户信息响应
type PacketGetProfileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User *SelfUser `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
}

func (x *PacketGetProfileRes) Reset() {
	*x = PacketGetProfileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_self_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketGetProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketGetProfileRes) ProtoMessage() {}

func (x *PacketGetProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_self_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketGetProfileRes.ProtoReflect.Descriptor instead.
func (*PacketGetProfileRes) Descriptor() ([]byte, []int) {
	return file_pb_packet_self_proto_rawDescGZIP(), []int{1}
}

func (x *PacketGetProfileRes) GetUser() *SelfUser {
	if x != nil {
		return x.User
	}
	return nil
}

// 修改当前用户信息
type PacketModfiyProfileReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NickName string `protobuf:"bytes,1,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"` //用户昵称
	Note     string `protobuf:"bytes,2,opt,name=note,proto3" json:"note,omitempty"`                         //个人说明
	Age      uint32 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`                          //年龄
	Sex      uint32 `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`                          //性别
}

func (x *PacketModfiyProfileReq) Reset() {
	*x = PacketModfiyProfileReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_self_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketModfiyProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketModfiyProfileReq) ProtoMessage() {}

func (x *PacketModfiyProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_self_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketModfiyProfileReq.ProtoReflect.Descriptor instead.
func (*PacketModfiyProfileReq) Descriptor() ([]byte, []int) {
	return file_pb_packet_self_proto_rawDescGZIP(), []int{2}
}

func (x *PacketModfiyProfileReq) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *PacketModfiyProfileReq) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *PacketModfiyProfileReq) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *PacketModfiyProfileReq) GetSex() uint32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

type PacketModfiyProfileRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RetCode RetCode `protobuf:"varint,1,opt,name=ret_code,json=retCode,proto3,enum=pb.RetCode" json:"ret_code,omitempty"` //响应状态码
}

func (x *PacketModfiyProfileRes) Reset() {
	*x = PacketModfiyProfileRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_packet_self_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketModfiyProfileRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketModfiyProfileRes) ProtoMessage() {}

func (x *PacketModfiyProfileRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_packet_self_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketModfiyProfileRes.ProtoReflect.Descriptor instead.
func (*PacketModfiyProfileRes) Descriptor() ([]byte, []int) {
	return file_pb_packet_self_proto_rawDescGZIP(), []int{3}
}

func (x *PacketModfiyProfileRes) GetRetCode() RetCode {
	if x != nil {
		return x.RetCode
	}
	return RetCode_Unknown
}

var File_pb_packet_self_proto protoreflect.FileDescriptor

var file_pb_packet_self_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x62, 0x2f, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x73, 0x65, 0x6c, 0x66,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0f, 0x70, 0x62, 0x2f, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x16, 0x70, 0x62, 0x2f,
	0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x15, 0x0a, 0x13, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x22, 0x37, 0x0a, 0x13, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x12, 0x20, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x65, 0x6c, 0x66, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x22, 0x6d, 0x0a, 0x16, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x6f, 0x64,
	0x66, 0x69, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a,
	0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f,
	0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x6f, 0x74, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73,
	0x65, 0x78, 0x22, 0x40, 0x0a, 0x16, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x6f, 0x64, 0x66,
	0x69, 0x79, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x08,
	0x72, 0x65, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b,
	0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x72, 0x65, 0x74,
	0x43, 0x6f, 0x64, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x62, 0x50, 0x00, 0x50, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_packet_self_proto_rawDescOnce sync.Once
	file_pb_packet_self_proto_rawDescData = file_pb_packet_self_proto_rawDesc
)

func file_pb_packet_self_proto_rawDescGZIP() []byte {
	file_pb_packet_self_proto_rawDescOnce.Do(func() {
		file_pb_packet_self_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_packet_self_proto_rawDescData)
	})
	return file_pb_packet_self_proto_rawDescData
}

var file_pb_packet_self_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pb_packet_self_proto_goTypes = []interface{}{
	(*PacketGetProfileReq)(nil),    // 0: pb.PacketGetProfileReq
	(*PacketGetProfileRes)(nil),    // 1: pb.PacketGetProfileRes
	(*PacketModfiyProfileReq)(nil), // 2: pb.PacketModfiyProfileReq
	(*PacketModfiyProfileRes)(nil), // 3: pb.PacketModfiyProfileRes
	(*SelfUser)(nil),               // 4: pb.SelfUser
	(RetCode)(0),                   // 5: pb.RetCode
}
var file_pb_packet_self_proto_depIdxs = []int32{
	4, // 0: pb.PacketGetProfileRes.user:type_name -> pb.SelfUser
	5, // 1: pb.PacketModfiyProfileRes.ret_code:type_name -> pb.RetCode
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pb_packet_self_proto_init() }
func file_pb_packet_self_proto_init() {
	if File_pb_packet_self_proto != nil {
		return
	}
	file_pb_packet_proto_init()
	file_pb_packet_entity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_packet_self_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketGetProfileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_self_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketGetProfileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_self_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketModfiyProfileReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_packet_self_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketModfiyProfileRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_packet_self_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_packet_self_proto_goTypes,
		DependencyIndexes: file_pb_packet_self_proto_depIdxs,
		MessageInfos:      file_pb_packet_self_proto_msgTypes,
	}.Build()
	File_pb_packet_self_proto = out.File
	file_pb_packet_self_proto_rawDesc = nil
	file_pb_packet_self_proto_goTypes = nil
	file_pb_packet_self_proto_depIdxs = nil
}
